
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { increment, decrement, incrementByAmount, decrementByAmount } from "../redux/counter";

export default function Home() {
  // const {count} = useSelector((state) => state.counter);
  const count = useSelector(state => state.counter.count);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Testing Dynamic Content{" "}
        <a
          href="https://designbyfaizi.me"
          target="_blank"
          rel="noreferrer"
          style={{ color: "#0070f3" }}
        >
          in Next
        </a>
      </h1>
      <h2>The count is: {count}</h2>
      <div>
        <button onClick={() => dispatch(increment())}>Increment</button>
        <button onClick={() => dispatch(decrement())}>Decrement</button>
        <button onClick={() => dispatch(incrementByAmount(5))}>Increment by 5</button>
        <button onClick={() => dispatch(decrementByAmount(5))}>Decrement by 5</button>
      </div>
    </div>
  );
}
